### ISSUE TITLE
More Information

### ISSUE THREAD

**Issue by BillyONeil** [Rack-Robotics/Powercore-V1-Hardware#1]
I have looked through your documentation, but cannot find any information on the AC power supply you are using. I have seen reference to 72v and 60v. 
Also could you also clarify the type of thermistor used

Great project, look forward to your reply

**Comment by John-RackRobotics** [comment]
The power supply is a 72 V, 600 W, SMPS. The thermister used is the same kind as on the Creality Ender 3, the 'NTC 3950'.

**Comment by 74HC14** [comment]
I will note that a cost-effective alternative to a 72V 600W SMPS would be a microwave oven transformer, with its secondary coil cut out and replaced with a bit of hand-winding. Plus a bridge rectifier, filter caps, and a fuse.
